timeout 100000; 
max_events 420;

server www/calc.com {           # Minimal calculator server

    types {                     # MIME types
        text/html html;
        text/css css;
        text/javascript js;
    }

    client_max_body_size 2000;  # Limit upload/body size
    host 127.0.0.4:8081;        # Different host:port from fusion_web
    root www/calc;              # Root directory for calculator site
    index calc.html;            # Default page

    error_page error.html;      # Optional: custom error fallback

    location / {
        root www/calc;
        index calc.html;
        allowed_methods GET;
    }
	    location /v2 {
        root www/calc;
        index v2.html;
        allowed_methods GET;
    }
}