timeout 50000;
max events 999;

server sussy {

	types {
		text/css css;
		text/html html;
		image/png png;
		image/jpeg jpeg;
		image/jpeg jpg;
	}

	client_max_body_size 4000;
	host 127.0.0.3:8081; 
	root www/cookies_test/; 
	index index.html; 

	error_page error.html;

	location /login { # if login location is present we will redirect you there before you can perfrom any request
		alias www/cookies_test/;
		index login.html;
		allowed_methods GET POST;
	}
}