timeout 100000; 
max_events 420;

server www/minigame.com {

    types {
        text/html html;
        text/css css;
        text/javascript js;
    }

    client_max_body_size 2000;  # Limit upload/body size
    host 127.0.0.5:8082;        # Different host:port from fusion_web
    root www/minigame;              # Root directory for site
    index minigame.html;            # Default page

    error_page error.html;      # Optional: custom error fallback

    location / {
        root www/minigame;
        index minigame.html;
        allowed_methods GET;
    }

}